### ISSUE TITLE
需求整理

### ISSUE THREAD

**Issue by helloztt** [mingshz/ShoppingBeauty#1]
**管理后台**
* 商户模块（管理员操作）
  * 商户列表
  * 添加商户
  * 重置密码
  * 冻结/启用商户

* 门店模块（商户登录后操作）
  * 门店列表
  * 添加门店
  * 冻结/启用门店
  * 添加门店代表
  * 冻结/启用门店代表

* 项目管理
  * 项目列表
  * 添加/编辑项目
  * 上/下架项目（批量下架门店项目）
  * 推荐/取消推荐项目（批量推荐门店项目）
  * 门店项目列表（什么门店下有什么项目）
  * 添加/编辑门店项目
  * 上/下架门店项目
  * 推荐/取消推荐门店项目

* 充值卡管理
  * 充值卡列表
  * 添加充值卡，批量生成卡密
  
* 用户模块
  * 用户列表搜索
  * 冻结/解冻用户
  * 用户详情
  * 充值
  * 提现（清零）
  * 用户余额日志

**前端**
* 微信授权
* 注册、登录
* 用户个人中心显示基本信息和余额、订单列表入口、最新推荐入口、充值入口、我的会员卡入口；
* 门店代表的个人中心显示门店扫码入口、订单列表入口（显示门店所有订单）；
* 门店代表扫用户会员卡，获取用户ID后进入门店项目列表，勾选项目并设置数量后生成订单（订单编号、用户编号、门店代表编号、门店编号、List{项目编号,名称,原价,折扣价,数量}，时间）；
* 用户'感知'有订单要付款了，就跳转到订单详情页，确认时判断余额是否充足，不充足先弹出充值窗口，金额=订单金额-余额，充值成功后扣款，设置订单状态为已支付，添加流水

**Comment by caijiang** [comment]
可解冻/冻结用户

涉及交易，支付类的实体 都应该将当时的交易情况（包括原价）都保留下来，而且这些数据绝非冗余。
