### ISSUE TITLE
将某用户设置为管理员，而且可以指定为何种管理员(审核专员，商户专员)

### ISSUE THREAD

**Issue by caijiang** [mingshz/ShoppingBeauty#12]
现有约定尚无法满足。

**Comment by helloztt** [comment]
目前管理员可定义为以下几种角色：
超级管理员：ROOT
财务：ROOT_SETTLEMENT
项目审核：AUDIT_ITEM

**Comment by caijiang** [comment]
我考，我弄错issue了
/manage/{id}/levelSet
已完成……
