### ISSUE TITLE
新增操作员，以及特定相关权限，比如门店专员, 项目专员，结算专员（可能是同一个人）

### ISSUE THREAD

**Issue by caijiang** [mingshz/ShoppingBeauty#16]
有类似接口，但没有实现特定权限。

**Comment by caijiang** [comment]
PUT /manage/{id}/levelSet

**Comment by caijiang** [comment]
是商户！商户！

**Comment by helloztt** [comment]
/store/{storeId}/represent/{representId} @caijiang 确认一下

**Comment by caijiang** [comment]
门店代表之前就完成了（至少协议是完成了）

这里讨论的是 商户的操作员；

**Comment by helloztt** [comment]
呀，接口复制错了。。。
是这个 /merchant/{merchantId}/manage/{manageId}

**Comment by caijiang** [comment]
若是editor明示 level这个数组可以放什么string 那也是极好的。

**Comment by helloztt** [comment]
done
