### ISSUE TITLE
新增项目协议调整建议

### ISSUE THREAD

**Issue by caijiang** [mingshz/ShoppingBeauty#18]
当前协议中，所需以下字段
### id
不应该需要该字段
### merchantId
很合理，必须
### name
很合理，必须，缺少字段约束，比如长度
### thumbnailUrl
很合理，必须，缺少向服务端推送图片资源，并且获得资源URL的逻辑。
### itemType
很合理，必须，缺少字段约束；比如只允许的列表
### price salesPrice costPrice description richDescription
很合理，
### recommended
不需要该字段，是否推荐 并不取决于商户！

**Comment by caijiang** [comment]
新增 POST /_resourceUpload/upload

**Comment by EllusionLee** [comment]
这里图片上传的过程,是页面上异步后台上传一张图片,响应到前台图片url
.新增/编辑项目的时候一起提交将其他信息一起与图片url 发送到后台吗?
