### ISSUE TITLE
实体与接口整理（先保存一下，未完待续）

### ISSUE THREAD

**Issue by helloztt** [mingshz/ShoppingBeauty#2]
**管理后台**
* 超级管理后台：管理员登录，维护商户、用户、充值卡、与商户的结算信息
* 商户管理后台：商户登录，维护门店和项目信息

**可登录角色（Login）：**
* 描述
    把可登录的角色抽象出来，下面角色都应该继承它
* 字段
    * 编号、登录名、密码、昵称、创建时间、启用状态、删除状态

**管理员（Manager）**：默认会有一个管理员；可登录超级管理后台（**新增**）
* 字段
    * 权限
* 接口
    * 新增管理员
    * 冻结/解冻管理员
    * 删除管理员

**商户（Merchant）：** 1个商户多个门店；可登录管理后台
* 字段
    * 联系人、电话
* 接口
    * 商户列表搜索
    * 添加/编辑，删除商户
    * 启用/冻结，重置密码

**门店（Store）：** 1个门店多个代表；可登录管理后台
* 字段
    * 联系人、电话、地址、经度、纬度
* 接口
    * 门店列表搜索
    * 添加/编辑，删除门店
    * 启用/冻结

**代表（Represent）：**；可微信端登录
* 字段
    * 性别
* 接口
    * 代表列表搜索
    * 添加/编辑，删除代表
    * 启用/冻结

**高端用户（User）：** 可微信端登录
* 字段
    * 性别、余额、是否是推广者、引导人
* 接口
    * 用户列表搜索（在超级管理）
    * 用户详情
    * 冻结/解冻用户
    * 充值/提现
    

**项目（Item）**
* 字段
    * 项目编号、图片{原图、大图、小图、缩略图}、名称、描述、类型、原价、销售价、结算价、介绍、推荐状态、上下架状态、删除状态
* 接口
    * 项目列表搜索
    * 添加/编辑，删除项目：删除后所有门店项目均删除
    * 上架/下架项目，推荐项目，修改销售价：操作后所有门店项目均上/下架
    
**门店项目（StoreItem）**
* 字段
    * 门店编号、项目编号、销售价、推荐状态、上下架状态
* 接口
    * 门店项目搜索
    * 添加/编辑，删除门店项目
    * 上下架项目，推荐项目，修改销售价

**用户账户流水日志（UserAmountLog）**
* 字段
    * 流水编号、用户、日志类型、金额变动、备注、生成时间
* 接口
    * 用户详情中可查看流水（流水的搜索做成通用的，会根据多种条件查询）

**充值卡（RechargeCard）**
* 字段
    * 编号、卡密、状态、用户编号、金额、生成时间、兑换时间
* 接口
    * 可根据金额批量生成卡密唯一的充值卡
    * 删除充值卡
    * 兑换充值卡

**订单（Order）**
* 字段
    * 编号、门店编号、商户编号、用户编号、门店代表编号、总金额、结算金额、订单状态、生成时间、支付时间、是否结算、结算单编号、结算时间
* 接口
    * 生成订单
    * 支付订单
    * 取消订单
    * 订单查询

**订单项目（OrderItem）**
* 字段
    * 订单项目编号、订单编号、项目编号、项目名称、原价、销售价、结算价、数量
* 接口
    * 跟着订单走~

**结算单（Settlement）**
* 字段
    * 结算单编号、商户编号、结算金额、变动金额、、状态{待提交、已打回、已审核、已打款、已收款}、备注、结算时间
*接口
    * 轮询根据订单生成结算单
    * 修改变动金额：结算状态为待提交或已打回时，商户可修改变动金额
    * 修改状态
    * 查询结算单

**Comment by helloztt** [comment]
有几个问题：
* 以上是否需要补充
* 充值卡是否需要考虑成一个 可销售的项目？还是说只是在门店销售？
    * 回答：不需要，只有线下购买渠道
* 如果由于商户设置的项目结算价有问题，导致产生的结算单金额与实际不符，这种情况是否有对应的流程？
* 商户上是否会有一个余额的概念，结算单生成后，它的余额相应增加；还是结算单上有个是否结算的状态
* 代表的订单列表显示门店所有列表，假设一个场景，代表A给用户下单，创建完发现错了准备取消订单，是否容易误操作，把他人的订单取消了；另外如果把他人订单取消了，也找不到是哪个代表操作的

**Comment by caijiang** [comment]
关于地址那块我可能会有现成的方案并入；关于百度定位的。

用户账户流水日志（UserAmountLog）我认为它是一个接口或者抽象类或者视图，但不应该是一个实体。
我说得很绕，但相信你应该明白了。

缺少了平台角色即管理员和推广者；

**推广者**
一个特定的邀请分享者，只有它可以邀请会员加入；这个会员体制除了是高门槛而且是封闭的。

比如在充值卡（RechargeCard）中不但应该存有操作生成的管理员也有具体的推广者。

**Comment by helloztt** [comment]
日志：你的意思是我定义的太具体了？把所有的日志抽象出来？

**Comment by caijiang** [comment]
* 如果由于商户设置的项目结算价有问题，导致产生的结算单金额与实际不符，这种情况是否有对应的流程？
在申请结算时，商户可同时提交 核增，核减数据；平台允许即可。说白了依然是过场，但很重要，虽然系统并不支撑现金流，但应该支撑完全的信息流
* 商户上是否会有一个余额的概念，结算单生成后，它的余额相应增加；还是结算单上有个是否结算的状态
没有余额，第二个选项很有意思；平台确认打款之后，商户打个勾 表示不再关心这个结算申请单。
* 代表的订单列表显示门店所有列表，假设一个场景，代表A给用户下单，创建完发现错了准备取消订单，是否容易误操作，把他人的订单取消了；另外如果把他人订单取消了，也找不到是哪个代表操作的
错了就错了，丢了它；再开一单 💯

**Comment by caijiang** [comment]
流水日志问题

并非你定义得太具体了，而是它本来就具体不了。
我们建模时只对现实负责，现实的情况就是只有充值订单，消费订单；日志是这些订单在另一个视角的表现形式。

所以按照第三范式，模型没有单独的流水日志；当然我们同样需要对「另一个视角」负责，所以可以采用技术方式解决这个问题，比如创建视图（显然是只读的）。

**Comment by caijiang** [comment]
还记得之前跟你聊过的「盘结问题」么

在业务规模扩张之后，可以创建真正的实体日志与之对应；比如**充值订单日志**；我们依然确保入口稳定，就是查询视图的时候除了原有查询（查询的是实际的订单）再union上我们的**充值订单日志**。

**Comment by helloztt** [comment]
就是说日志无需记录，而是直接从它产生的地方获取，比如消费订单，我可以直接从订单里读数据。

我觉得这样的设计在 数据可变 的场景下更适用 ，比如 库存，由于商品存在退货的情况，所以在某一时间段内的库存变动得从订单中读取，那么此时的库存=上一次盘结库存+变动库存，下一次盘结时维护 库存字段。
用户账户流水，是和财务挂钩的，从专业角度来看，财务的凭证是不存在变动的，如果有错误只能红字反冲；

如果不需要这么专业，直接从订单中读取当然是可行的，那么充值的操作也要生成一笔订单吗？
