### ISSUE TITLE
后台管理场景-结算单

### ISSUE THREAD

**Issue by helloztt** [mingshz/ShoppingBeauty#26]
* 字段
  * 结算单编号、商户编号、门店编号、结算金额、变动金额、状态{待提交、待审核、已打回、已审核、已打款、已收款}、备注、生成时间、打款时间、订单列表

* 接口
  * 轮询生成结算单。遍历门店编号，根据 结算周期T（系统变量）获取可结算（settled == false and currentLocalDate >=(payTime+ T + 1)）的订单，一次轮询同一门店生成一笔结算单，并修改 MainOrder.settled 以及 MainOrder.settleId。
  * 商户财务可对 待提交、已打回 的结算单修改变动金额，并提交平台审核
  * 平台财务可对 待审核 的结算单进行审核操作{打回、审核通过}
  * 平台财务可对 已审核 的结算单进行打款操作{已打款}
  * 商户财务可对 已收款 的结算单进行收款操作{已收款}

**Comment by caijiang** [comment]
确保数据原子性。

若是MainOrder真的记录了 settled  这个量可能会引发异常状态：即存在重复结算的可能性。

在主订单上增加到结算单的关联，只有主订单没有结算单或者有「已撤销」，「已打回」的结算单的情况下可以被获得新的结算单。

不直接关联门店，但很显然我们可以根据现有数据获得一份结算单的门店明细。
金额同样来自该结算单相关联（可使用双向关联）的订单列表+变动金额。

商户在可以对「待提交」的结算单执行「撤销」动作。
「已撤销」和「已打回」的结算单无法查看明细，只可以被删除。

## 结算单(实体设计)
* 结算单编号
* 商户编号
* 变动金额
* 实际转账金额
* 状态{待提交、待审核、已打回、已审核、已打款、已收款，已撤销}
* 备注
* 生成时间
* 打款时间
