### ISSUE TITLE
关于 HttpStatus 与 resultCode 的定义

### ISSUE THREAD

**Issue by helloztt** [mingshz/ShoppingBeauty#4]
* HttpStatusCustom（基于HttpStatus做一些拓展）
  * 请求成功： HttpStatusCustom.SC_OK = 200
  * 请求不合规： HttpStatusCustom.SC_DATA_NOT_VALIDATE = 210
  * 未登录： HttpStatusCustom.SC_UNAUTHORIZED = 401
  * 不允许操作：HttpStatusCustom.SC_FORBIDDEN = 403
  * 系统正在维护：HttpStatusCustom.SC_SYSTEM_MAINTENANCE = 508
  * 系统故障 : HttpStatusCustom.SC_INTERNAL_SERVER_ERROR = 500
  * **待补充...**

* ResultCodeEnum（定义请求为啥不合规的说明）
  * 说明：code 从 1000 开始定义，每个模块最多 1000 个状态码定义，状态码区间分配如下，如果后续添加模块请自行补充
  * 注册、登录、权限相关：[1000,1999]
  * 用户、推荐：[2000,2999]
  * 项目、门店：[3000,3999]
  * 订单相关：[4000,4999]
  * 支付、充值：[5000,5999]
  * 结算单相关: [6000,6999]
  * **待补充...**

@caijiang @chang0022 @EllusionLee 确认一下。

**Comment by helloztt** [comment]
ResultCodeEnum 的定义 @chang0022
https://github.com/mingshz/ShoppingBeauty/blob/master/service/src/main/java/com/ming/shopping/beauty/service/model/ResultCodeEnum.java

**Comment by caijiang** [comment]
* 4011 -> 430
* 4012 -> 431
* 4013 -> 432
* 4041 -> 433
因部分现代http服务器或者浏览器并不支持4位响应做次调整。

按照RFC的资料 4XX保留417以上，5XX保留505以上。
