### ISSUE TITLE
2.26测试问题

### ISSUE THREAD

**Issue by deleiye** [mingshz/ShoppingBeauty#46]
1. 商户在后台新增管理员后，查看不到新增的管理员

1. 扫描会员卡二维码后选择项目结算。一直显示提交中，无法结算。
![_20180226140037](https://user-images.githubusercontent.com/25718181/36655408-7452a0fa-1afd-11e8-89b9-1911df8a5684.jpg)

**Comment by caijiang** [comment]
分分开呗…………

商户管理员？你是说商户操作员么？ 那个商户？

**Comment by caijiang** [comment]
https://github.com/mingshz/ShoppingBeauty/wiki/WorkWithStaging

**Comment by caijiang** [comment]
问题2:

只有店主或者门店代表可以扫这个码。

**Comment by deleiye** [comment]
商户手机号：13666611567
![_20180226142709](https://user-images.githubusercontent.com/25718181/36656030-301777b8-1b01-11e8-9f5b-25ecceb877fc.png)

**Comment by chang0022** [comment]
问题2，我修改了。普通用户无法操作门店页面

**Comment by caijiang** [comment]
问题1 正在检查中。
@deleiye 丫的 以后问题分开发

**Comment by helloztt** [comment]
问题1 已修复 @deleiye
