### ISSUE TITLE
商户管理接口疑问

### ISSUE THREAD

**Issue by caijiang** [mingshz/ShoppingBeauty#9]
GET
/merchant/{merchantId}/manage

管理后台商户操作员列表
GET
/merchant/{merchantId}/manage/{manageId}

操作员详情
POST
/merchant/{merchantId}/manage/{manageId}

新增操作员
PUT
/merchant/{merchantId}/manage/{manageId}

启用/禁用操作员

以上管理接口都要求传入 merchantId 但是获取商户的数据中并没有 merchantId 的结果。

**Comment by helloztt** [comment]
/manageLoginResult/{id} 登录后如果为商户会返回 merchantId

**Comment by caijiang** [comment]
使用场景是：管理员管理商户

总不成每次管理员要管理商户的时候 都以该商户身份先登录吧？

**Comment by helloztt** [comment]
使用场景应该是：1.管理员管理商户的操作员 或 2.商户管理自己的操作员
1场景应该从商户列表中进行操作，那么自然是有merchantId的
2场景应该是登录后保存merchantId到cookies？然后读取当前登录的所属商户ID

**Comment by helloztt** [comment]
管理商户是
GET/POST
/merchant

**Comment by caijiang** [comment]
>  {
      "loginId": 0,
      "username": "string",
      "name": "string",
      "contact": "string",
      "telephone": "string",
      "address": "string",
      "enabled": true,
      "createtime": "string"
    }

是的，响应的数据中没有merchantId；但是后面的管理都需要用到。
